dmmwebcamp-8bit/nagano-cake

db/migrate/20230515063617_create_active_storage_tables.active_storage.rb, db/schema.rb
=> [Add] install ActiveStorage

app/models/address.rb, app/models/cart_item.rb, app/models/genre.rb, app/models/item.rb, app/models/order.rb, app/models/order_detail.rb, db/migrate/20230515064830_create_addresses.rb, db/migrate/20230515064921_create_orders.rb, db/migrate/20230515065100_create_order_details.rb, db/migrate/20230515065150_create_genres.rb, db/migrate/20230515065212_create_cart_items.rb, db/migrate/20230515065241_create_items.rb, db/schema.rb, test/fixtures/addresses.yml, test/fixtures/cart_items.yml, test/fixtures/genres.yml, test/fixtures/items.yml, test/fixtures/order_details.yml, test/fixtures/orders.yml, test/models/address_test.rb, test/models/cart_item_test.rb, test/models/genre_test.rb, test/models/item_test.rb, test/models/order_detail_test.rb, test/models/order_test.rb
=> [Add] migration_files

app/models/customer.rb
=> [Add] Customer association

app/models/customer.rb
=> Association sasamao

app/models/customer.rb, app/models/genre.rb, app/models/item.rb
=> [Add] itemのアソシエーションを記述

app/models/order.rb
=> [Add] association_order

app/models/address.rb, app/models/cart_item.rb, app/models/genre.rb, app/models/item.rb, app/models/order_detail.rb
=> [Add]association

.gitignore, Gemfile, Gemfile.lock, app/javascript/packs/application.js, app/javascript/stylesheets/application.scss, app/models/order.rb, app/models/order_detail.rb, app/views/layouts/application.html.erb, config/application.rb, config/environments/development.rb, config/locales/ja.yml, config/webpack/environment.js, package.json, yarn.lock
　model: order
　　payment_method
　　status
　model: order_details
　　making_status
　ADMIN_EMAIL, ADMIN_PASSの設定
=> [Add] setup-gems

app/assets/stylesheets/admin/order_details.scss, app/controllers/admin/order_details_controller.rb, app/helpers/admin/order_details_helper.rb, config/routes.rb, test/controllers/admin/order_details_controller_test.rb
#全ルーディング記述
※order_detailsコントローラー作成
=> Setup routing

app/views/public/homes/top.html.erb
=> [Update] topビューのレイアウトを調整

app/controllers/admin/sessions_controller.rb, app/views/admin/sessions/new.html.erb, db/seeds.rb
- Admin.create!　で管理者登録
- new.html.erb　管理者ログインページ作成
※動作確認済み
- after_sign_in_pathの設定
=> [Add]管理者ログイン機能

app/controllers/admin/genres_controller.rb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb
- admin/genres_controller.rb
- admin/genres/index.html.erb
- admin/genres/edit.html.erb
=> [Update] admin/genres配下のコントローラ/ビュー内への記述

app/controllers/public/cart_items_controller.rb, app/views/layouts/_header.html.erb, app/views/public/cart_items/index.html.erb, config/routes.rb
・indexの詳細表示
・update機能
・destroy機能
・destroy_all機能
・create機能
cart_item_paramsの実装
=> [Add] cart_items

app/controllers/admin/customers_controller.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/public/registrations/new.html.erb
- 各ページのアクション記述
- 会員情報更新機能追加
- 会員一覧ページ作成
- ページネーション
- 会員情報編集ページ作成
- 会員詳細ページ作成
=> [Add]会員一覧/会員詳細/会員情報編集/更新機能

app/views/admin/homes/top.html.erb, config/application.rb, config/locales/ja.yml
- タイムゾーンを日本時間に変更
- created_atフォーマット
=> [Update]タイムゾーンを日本時間に変更

app/controllers/admin/order_details_controller.rb, app/controllers/admin/orders_controller.rb, app/controllers/public/cart_items_controller.rb, app/controllers/public/orders_controller.rb
* admin/order_detail controller
+ before_action :authenticate_admin!
* admin/order_controller
+ before_action :authenticate_admin!
* public/cart_items_controller
+ before_action :authenticate_customer!
* public/order_controller
+ before_action :authenticate_customer!
=> [Finish] restrict-access

app/controllers/admin/customers_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/registrations_controller.rb, app/controllers/public/sessions_controller.rb, app/models/customer.rb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/layouts/_flash.html.erb, app/views/public/customers/confirm.html.erb, app/views/public/customers/show.html.erb, config/locales/devise.ja.yml
セイ・メイ　⇒全角カタカナのみ
郵便番号　　⇒整数のみ・８文字制限
電話番号　　⇒整数のみ
２秒後にスライドアップされるよう設定
app/views/public/customers/show.html.erb
app/views/public/customers/confirm.html.erb
app/views/admin/customers/show.html.erb
- 変更前
```
<% if customer.is_deleated == false %>
　<p class="text-success font-weight-bold">有効</p>
<% else %>
　<p class="text-secondary font-weight-bold">退会</p>
<% end %>
```
- 変更後
```
<% if customer.is_deleated %>
　<p class="text-secondary font-weight-bold">退会</p>
<% else %>
　<p class="text-success font-weight-bold">有効</p>
<% end %>
```
config/locales/devise.ja.ymlconfig/locales/devise.ja.yml
=> Fix customers

app/controllers/admin/genres_controller.rb, app/controllers/admin/items_controller.rb, app/controllers/public/addresses_controller.rb, app/models/address.rb, app/models/genre.rb, app/models/item.rb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/items/edit.html.erb, app/views/admin/items/new.html.erb, app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb, config/locales/ja.yml
- admin/genres
- admin/items
┗ 商品登録ページのジャンル選択欄に対しrequire: trueを設定
- public/addresses
=> [Update] バリデーションの追加、エラーメッセージの設定

app/views/public/homes/_information.html.erb, app/views/public/homes/top.html.erb, app/views/public/items/index.html.erb
=> [Finish] last-fix

app/controllers/public/sessions_controller.rb, app/models/genre.rb
=> [Finish] last-last-fix
